/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      fontFamily: {
        "bi-neo-bold": ["BI_neo_bold", "sans-serif"],
        "bi-neo-bold-italic": ["BI_neo_bold_italic", "sans-serif"],
        "bi-neo-black": ["BI_neo_black", "sans-serif"],
        "bi-neo-black-italic": ["BI_neo_black_italic", "sans-serif"],
      },
      colors: {
        "bi-yellow": "#FFB81C",
        "blue-dark": "#003865",
        "blue-line": "#173961",
        "blue-light": "#00C1D4",
        "blue-divider": "#173961",
        "digital-aqua": "#00C1D4",
        "digital-blue": "#2C8B9E",
        "gray-disabled": "#D9D9D9",
        "digital-gray": "#8C8C8C",
        "dark-gray": "#535252",
        divider: "#ffffff3b",
        "gray-ultra-light": "#F8F8F8",
        "gray-light": "#F5F5F5",
        "gray-semi-light": "#858585",
        "gray-dark": "#5C5B5B",
        "gray-semi-dark": "#909090",
        "desktop-gray": "#666666",
        "desktop-header-gray": "#F5F4F4",
        "btn-gray": "#E6E5E5",
      },
      fontSize: {
        "desktop-title-3": "48px",
        "desktop-title-2": "40px",
        "desktop-title-1": "32px",
        "desktop-subtitle-2": "28px",
        "desktop-subtitle-1": "25px",
        "desktop-subtitle-alt-2": "22px",
        "desktop-subtitle-alt-1": "18px",
        "mobil-subtitle-alt-1": "16px",
        title: "24px",
        subtitle: "18px",
        content: "15px",
      },
      boxShadow: {
        normal: "0px 2px 5px rgba(0, 0, 0, 0.15)",
        header: "0 0 2px 3px rgba(0, 0, 0, .5)",
      },
    },
  },
  plugins: [],
};
